name: Super-Linter

on:  
  push:
  pull_request:
    branches:
      - main
 

jobs:
  trigger-a-jenkins-job:
    runs-on: ubuntu-latest
    steps:
      - id: triggerjenkinsjob
        uses: estherk0/jenkins-trigger@1.0
        with:
          jenkins-server:  "http://100.20.0.129:8080" # URL of the jenkins server. ex: http://myjenkins.acme.com:8080
          jenkins-job: "gitactions" # The name of the jenkins job to run
          jenkins-username: admin# user name for accessing jenkins
          jenkins-pat: "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" # personal Access token for accessing Jenkins
          poll-time: 10 # how often (seconds) to poll the jenkins server for results
          timeout-value: 600 # How long (seconds) to poll before timing out the action
          verbose: true # true/false - turns on extra logging
