name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: "http://100.20.0.129:8080/"
          user: "admin"
          token: ${{ secrets.TOKEN }}
      
      - name: Super-Linter
        uses: github/super-linter@v4.9.5
        env:
          DEFAULT_BRANCH: main;
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
